# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5ab94fcc72f4c61e6af1e1c571e590ec1c618021009cfe24e7ecc460a816124d3210fb157fa34ee9688dffd484ed15d64f3cfab70e35aa87aeafe3df496e4d3

test:
  secret_key_base: eeacf91da3a39847295176741b8073fea94824434dd0bb0389a6f8db7d278854ad769ffdb4a792434352835b83bc39a22c3255ccfe284de0a09fff940b73f9aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
