# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6bd01a239bc9700327e15e79e0b66f0e1d7c6678f0f69777c3caa5a776c3e7a77a9c31ffc8d5ac61b70b4f3303cc489142dfdf5784f90897d312c9e223523f5

test:
  secret_key_base: aaa6235d765974e8e71d5e5ba099a5e696798059aebed5b8e94171b3e853777f0fa37d1df974f176366fb074ce26412df2b38a7c6594364614cf305bcd2e2d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
